// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230220101101_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            CategoryName = "Закуска",
                            Description = "Жареное или печёное тесто с начинкой. Размер и форма различны, но наиболее распространённая в виде треугольника. Часто подаётся с соусами.",
                            ImageUrl = "",
                            Name = "Самоса",
                            Price = 15m
                        },
                        new
                        {
                            ProductID = 2L,
                            CategoryName = "Закуска",
                            Description = "Индийское блюдо, приготовленное из кусочков панира, маринованных в специях и приготовленных на гриле в тандыре. Это вегетарианская альтернатива куриной тикке и другим мясным блюдам. Это популярное блюдо широко доступно в Индии и странах с индийской диаспорой",
                            ImageUrl = "",
                            Name = "Панир тикка",
                            Price = 13.99m
                        },
                        new
                        {
                            ProductID = 3L,
                            CategoryName = "Десерт",
                            Description = "Хлебобулочное изделие из теста с начинкой, которое выпекается или жарится",
                            ImageUrl = "",
                            Name = "Сладкий пирог",
                            Price = 10.99m
                        },
                        new
                        {
                            ProductID = 4L,
                            CategoryName = "Первое блюдо",
                            Description = "Блюдо быстрого питания из Индии, состоящее из густого овощного карри, которое подается с мягкой булочкой. Он возник в городе Мумбаи.",
                            ImageUrl = "",
                            Name = "Пав бхаджи",
                            Price = 15m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
